[package]
name = "lipsum"
version = "0.1.0"
edition = "2021"

[lib]
name = "lipsum"
path = "src/lib/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
rand = "0.8.5"
